"""Unit tests for `models/orm/` -- the mappings, their constraints and their shape.

Three kinds of assertion live here, and they fail for three different reasons.

**Behavioural.** Rows round-trip, enum columns come back as members, checks
reject what they were written to reject, cascades fire. These run against SQLite
(`tests/conftest.py`), which is enough because every constraint under test is
plain SQL that both engines enforce identically. Anything PostgreSQL-specific --
`JSONB` operators, partial-index planning, `TIMESTAMPTZ` fidelity -- belongs in
`tests/integration/db/`.

**Structural.** Every constraint and index carries a name generated by the
convention in `models/orm/base.py`. This is not style. An unnamed constraint gets
a server-generated name that differs between "created by `CREATE TABLE`" and
"created by `ALTER TABLE`", so the Alembic migration that created it cannot drop
it -- discovered on the downgrade path, months later, in production.

**Prohibitive.** `docs/data-stores.md` §3.1 forbids PostgreSQL from holding
payload bodies, embedding vectors and plaintext credentials. Those are the three
mistakes that quietly break the two-tier rule the whole storage design rests on,
and none of them announces itself: the schema still works, the rebuild guarantee
just stops being true. Asserting on column names and types is the cheapest place
to catch a column that should never have been added.
"""

from __future__ import annotations

import importlib
import pkgutil
import re
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime
from typing import Any

import pytest
from sqlalchemy import (
    ARRAY,
    CheckConstraint,
    Constraint,
    ForeignKeyConstraint,
    Index,
    LargeBinary,
    PrimaryKeyConstraint,
    String,
    Table,
    UniqueConstraint,
    and_,
    func,
    inspect,
    select,
    text,
)
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

import models.orm
from models.artifact import ArtifactKind, ArtifactOutcome, ArtifactState
from models.enums import (
    AgentName,
    AuthType,
    InvestigationStatus,
    Platform,
    SignalStatus,
    SourceCategory,
)
from models.feature import MembershipMethod
from models.identity import LinkMethod
from models.orm.artifact import ArtifactRow, PersonRow, SourceRow
from models.orm.base import Base, TolerantEnumType, metadata

# Every assertion below is over `metadata.tables`, so what this module can see
# depends entirely on which mapping modules have been imported. The explicit
# imports that follow cover the tables these tests name individually; this walk
# covers the rest, and is what makes the *cross-cutting* checks -- "every enum
# column is tolerant", "every foreign key declares an action" -- mean what they
# say.
#
# Without it those checks silently graded a subset. A table whose module nothing
# else imported was simply absent, and whether it appeared depended on test
# order: `test_artifact_orm.py` sorts before this file and imports its mappings,
# so the same assertion passed in a full run and failed when run alone.
from models.orm.connector_account import (
    ConnectorAccountRow,
    ConnectorAccountStatus,
    ConnectorCursorRow,
)
from models.orm.feature import FeatureLinkRow, FeatureRow, VersionRow
from models.orm.identity import IdentityLinkRow, IdentityRow
from models.orm.investigation import InvestigationRow, InvestigationStepRow, StepStatus
from models.orm.mixins import DEFAULT_TENANT
from models.orm.project import ProjectRow
from models.orm.report import (
    CitationRow,
    ReportFormat,
    ReportRow,
    ReportSectionRow,
    ReportStatus,
)
from models.orm.run import AgentRunRow, RunStatus, TraceRow
from models.orm.signal import SignalRow

for _module in pkgutil.iter_modules(models.orm.__path__):
    importlib.import_module(f"{models.orm.__name__}.{_module.name}")

pytestmark = pytest.mark.unit

TS = datetime(2026, 7, 28, 14, 2, 11, tzinfo=UTC)
FETCHED_AT = datetime(2026, 7, 28, 14, 29, 55, tzinfo=UTC)

NAIVE_TS = TS.replace(tzinfo=None)
"""What SQLite gives back for `TS`.

SQLite has no timestamp type: `DateTime(timezone=True)` compiles to `DATETIME`
and the dialect's bind processor formats the wall-clock fields, dropping the
offset. Values therefore return naive. That is a property of the test engine, not
of the mapping -- `TIMESTAMPTZ` fidelity is asserted against real PostgreSQL in
`tests/integration/db/`. Everything below writes UTC, so the wall clock is the
instant and the round-trip assertions stay meaningful.
"""


# --------------------------------------------------------------------------- #
# Row builders and seeders
#
# A seeder inserts one valid row of its table plus whatever parents its foreign
# keys require, and commits. Having one per table is what lets the enum and
# round-trip tests be generated from `Base.metadata` rather than hand-written per
# column -- a new table or a new enum column is then covered by construction, and
# the coverage tests below fail loudly if a seeder is missing.
# --------------------------------------------------------------------------- #


def make_signal(**overrides: Any) -> SignalRow:
    values: dict[str, Any] = {
        "id": "sig_1",
        "native_id": "t3_1abcde",
        "source": SourceCategory.SOCIAL,
        "platform": Platform.REDDIT,
        "url": "https://reddit.com/r/devops/comments/1abcde",
        "author_platform_id": "t2_9xyz",
        "author_handle": "ops_gremlin",
        "timestamp": TS,
        "fetched_at": FETCHED_AT,
        "content_text": "Our observability bill tripled after the renewal.",
        "content_char_count": 49,
        "connector_slug": "reddit",
    }
    return SignalRow(**(values | overrides))


def make_connector_account(**overrides: Any) -> ConnectorAccountRow:
    values: dict[str, Any] = {
        "id": "acct_1",
        "connector_slug": "reddit",
        "platform": Platform.REDDIT,
        "display_name": "Reddit -- devops watch",
        "auth_type": AuthType.OAUTH2,
        "params": {"subreddits": ["devops", "sre"]},
        "params_hash": "h" * 64,
    }
    return ConnectorAccountRow(**(values | overrides))


def make_connector_cursor(**overrides: Any) -> ConnectorCursorRow:
    values: dict[str, Any] = {
        "id": "cur_1",
        "connector_slug": "reddit",
        "account_id": "acct_1",
        "params_hash": "h" * 64,
        "cursor": {"page_token": "t3_zzz"},
        "watermark": TS,
    }
    return ConnectorCursorRow(**(values | overrides))


def make_investigation(**overrides: Any) -> InvestigationRow:
    values: dict[str, Any] = {
        "id": "inv_1",
        "query": "Why did observability spend spike this quarter?",
        "created_by": "ops@example.com",
    }
    return InvestigationRow(**(values | overrides))


def make_investigation_step(**overrides: Any) -> InvestigationStepRow:
    values: dict[str, Any] = {
        "id": "step_1",
        "investigation_id": "inv_1",
        "sequence": 0,
        "agent": AgentName.PLANNER,
        "input": {"question": "why?"},
    }
    return InvestigationStepRow(**(values | overrides))


def make_report(**overrides: Any) -> ReportRow:
    values: dict[str, Any] = {
        "id": "rep_1",
        "investigation_id": "inv_1",
        "title": "Observability spend, Q3",
        "summary": "Spend rose 3x after the renewal.",
        "confidence": 0.72,
    }
    return ReportRow(**(values | overrides))


def make_report_section(**overrides: Any) -> ReportSectionRow:
    values: dict[str, Any] = {
        "id": "sec_1",
        "report_id": "rep_1",
        "ordinal": 0,
        "heading": "What changed",
        "body": "The renewal moved the contract to on-demand pricing.",
        "confidence": 0.8,
    }
    return ReportSectionRow(**(values | overrides))


def make_citation(**overrides: Any) -> CitationRow:
    values: dict[str, Any] = {
        "id": "cit_1",
        "report_id": "rep_1",
        "section_id": "sec_1",
        "signal_id": "sig_1",
        "quote": "our observability bill tripled",
        "char_start": 4,
        "char_end": 34,
        "relevance": 0.91,
    }
    return CitationRow(**(values | overrides))


def make_agent_run(**overrides: Any) -> AgentRunRow:
    values: dict[str, Any] = {
        "id": "run_1",
        "investigation_id": "inv_1",
        "agent": AgentName.RETRIEVER,
        "model": "claude-sonnet-5",
        "prompt_id": "retriever.hybrid",
        "prompt_version": "v1",
        "prompt_hash": "a" * 64,
        "input_tokens": 1200,
        "output_tokens": 340,
        "cost_usd": 0.014400,
        "latency_ms": 2100,
        "started_at": TS,
    }
    return AgentRunRow(**(values | overrides))


def make_trace(**overrides: Any) -> TraceRow:
    values: dict[str, Any] = {
        "id": "trc_1",
        "trace_id": "a" * 32,
        "span_id": "b" * 16,
        "parent_span_id": "c" * 16,
        "name": "agent.retriever.hybrid_search",
        "attributes": {"k": 20},
        "agent_run_id": "run_1",
    }
    return TraceRow(**(values | overrides))


async def _add[T: Base](session: AsyncSession, row: T) -> T:
    session.add(row)
    await session.commit()
    return row


async def seed_signal(session: AsyncSession) -> SignalRow:
    return await _add(session, make_signal())


async def seed_connector_account(session: AsyncSession) -> ConnectorAccountRow:
    return await _add(session, make_connector_account())


async def seed_connector_cursor(session: AsyncSession) -> ConnectorCursorRow:
    await seed_connector_account(session)
    return await _add(session, make_connector_cursor())


async def seed_investigation(session: AsyncSession) -> InvestigationRow:
    return await _add(session, make_investigation())


async def seed_investigation_step(session: AsyncSession) -> InvestigationStepRow:
    await seed_investigation(session)
    return await _add(session, make_investigation_step())


async def seed_report(session: AsyncSession) -> ReportRow:
    await seed_investigation(session)
    return await _add(session, make_report())


async def seed_report_section(session: AsyncSession) -> ReportSectionRow:
    await seed_report(session)
    return await _add(session, make_report_section())


async def seed_citation(session: AsyncSession) -> CitationRow:
    await seed_report_section(session)
    return await _add(session, make_citation())


async def seed_agent_run(session: AsyncSession) -> AgentRunRow:
    await seed_investigation(session)
    return await _add(session, make_agent_run())


async def seed_trace(session: AsyncSession) -> TraceRow:
    await seed_agent_run(session)
    return await _add(session, make_trace())


def make_project() -> ProjectRow:
    return ProjectRow(
        id="prj_1",
        slug="omnisense",
        name="OmniSense",
        description="the developer platform",
    )


async def seed_project(session: AsyncSession) -> ProjectRow:
    """Idempotent, unlike the other seeders, because it is the shared root.

    Two seeders now reach it by different paths -- `seed_feature_link` needs both
    a feature (project -> version -> feature) and an artifact (project -> source
    -> artifact) -- and inserting twice fails on the primary key. The failure
    names `projects`, which is nowhere near the table being tested.
    """
    existing = await session.get(ProjectRow, "prj_1")
    if existing is not None:
        return existing
    return await _add(session, make_project())


def make_source() -> SourceRow:
    return SourceRow(
        id="src_1",
        project_id="prj_1",
        platform=Platform.GITHUB,
        external_id="R_kgDOABCD1M",
        name="omnisense/api",
        default_branch="main",
    )


def make_person() -> PersonRow:
    return PersonRow(
        id="per_1",
        platform=Platform.GITHUB,
        external_id="MDQ6VXNlcjE=",
        handle="dsokolov",
    )


def make_version() -> VersionRow:
    return VersionRow(id="ver_1", project_id="prj_1", name="v1")


def make_feature() -> FeatureRow:
    return FeatureRow(id="ftr_1", project_id="prj_1", version_id="ver_1", name="image upload")


def make_feature_link() -> FeatureLinkRow:
    return FeatureLinkRow(
        feature_id="ftr_1",
        artifact_id="art_1",
        method=MembershipMethod.BRANCH,
        confidence=0.8,
    )


def make_identity() -> IdentityRow:
    return IdentityRow(id="idn_1", display_name="Dmitri Sokolov")


def make_identity_link() -> IdentityLinkRow:
    return IdentityLinkRow(
        person_id="per_1",
        identity_id="idn_1",
        platform=Platform.GITHUB,
        method=LinkMethod.CONFIRMED,
        confidence=1.0,
    )


def make_artifact() -> ArtifactRow:
    return ArtifactRow(
        id="art_1",
        kind=ArtifactKind.CI_RUN,
        source_id="src_1",
        actor_id="per_1",
        platform=Platform.GITHUB,
        native_id="WFR_1",
        title="Run tests",
        occurred_at=TS,
        state=ArtifactState.COMPLETED,
        outcome=ArtifactOutcome.FAILURE,
    )


async def seed_source(session: AsyncSession) -> SourceRow:
    await seed_project(session)
    return await _add(session, make_source())


async def seed_person(session: AsyncSession) -> PersonRow:
    return await _add(session, make_person())


async def seed_version(session: AsyncSession) -> VersionRow:
    await seed_project(session)
    return await _add(session, make_version())


async def seed_feature(session: AsyncSession) -> FeatureRow:
    await seed_version(session)
    return await _add(session, make_feature())


async def seed_feature_link(session: AsyncSession) -> FeatureLinkRow:
    await seed_feature(session)
    await seed_artifact(session)
    return await _add(session, make_feature_link())


async def seed_identity(session: AsyncSession) -> IdentityRow:
    return await _add(session, make_identity())


async def seed_identity_link(session: AsyncSession) -> IdentityLinkRow:
    await seed_person(session)
    await seed_identity(session)
    return await _add(session, make_identity_link())


async def seed_artifact(session: AsyncSession) -> ArtifactRow:
    await seed_source(session)
    await seed_person(session)
    return await _add(session, make_artifact())


SEEDERS: dict[str, Callable[[AsyncSession], Awaitable[Any]]] = {
    "projects": seed_project,
    "sources": seed_source,
    "people": seed_person,
    "identities": seed_identity,
    "identity_links": seed_identity_link,
    "versions": seed_version,
    "features": seed_feature,
    "feature_links": seed_feature_link,
    "artifacts": seed_artifact,
    "signals": seed_signal,
    "connector_accounts": seed_connector_account,
    "connector_cursors": seed_connector_cursor,
    "investigations": seed_investigation,
    "investigation_steps": seed_investigation_step,
    "reports": seed_report,
    "report_sections": seed_report_section,
    "citations": seed_citation,
    "agent_runs": seed_agent_run,
    "traces": seed_trace,
}

MODELS: dict[str, type[Any]] = {
    "projects": ProjectRow,
    "sources": SourceRow,
    "people": PersonRow,
    "identities": IdentityRow,
    "identity_links": IdentityLinkRow,
    "versions": VersionRow,
    "features": FeatureRow,
    "feature_links": FeatureLinkRow,
    "artifacts": ArtifactRow,
    "signals": SignalRow,
    "connector_accounts": ConnectorAccountRow,
    "connector_cursors": ConnectorCursorRow,
    "investigations": InvestigationRow,
    "investigation_steps": InvestigationStepRow,
    "reports": ReportRow,
    "report_sections": ReportSectionRow,
    "citations": CitationRow,
    "agent_runs": AgentRunRow,
    "traces": TraceRow,
}


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def tables() -> list[Table]:
    """Every mapped table, ordered by name.

    Looked up through `.name` rather than through the `metadata.tables` keys:
    `bind_for_testing()` clears `Table.schema` but leaves the dictionary keyed by
    the original `omnisense.`-qualified string, so the keys and `Table.key`
    disagree for the whole unit run.
    """
    return sorted(metadata.tables.values(), key=lambda t: t.name)


def table_named(name: str) -> Table:
    return next(t for t in tables() if t.name == name)


async def reload[T: Base](session: AsyncSession, model: type[T], pk: str) -> T:
    """Re-read a row from the database, bypassing the identity map.

    `expunge_all()` first. With `expire_on_commit=False` a plain `SELECT` returns
    the instance the session already holds, still carrying whatever Python put
    there -- so an assertion on it can pass even if nothing was ever written.
    Dropping the instance forces the assertions onto what the database actually
    stored, which is the only thing a round-trip test is about.
    """
    session.expunge_all()
    return (await session.execute(select(model).where(model.id == pk))).scalar_one()


async def reload_row[T: Base](session: AsyncSession, row: T) -> T:
    """`reload`, for a row whose key is not a single column called `id`."""
    model = type(row)
    clause = _pk_filter(model, row)
    session.expunge_all()
    return (await session.execute(select(model).where(clause))).scalar_one()


def _pk_filter(model: type[Base], row: Base) -> Any:
    """A WHERE clause selecting exactly `row`, whatever its key looks like.

    Most tables here key on a column called `id`, and this used to assume both --
    the name and that there was only one. `identity_links` keys on `person_id`,
    and `feature_links` on the *pair* `(feature_id, artifact_id)`, both
    deliberately: an account belongs to one human, while an artifact genuinely
    belongs to several features. Reading the key off the mapper means a table with
    a natural or composite key needs no special case here.
    """
    return and_(
        *(
            getattr(model, column.name) == getattr(row, column.name)
            for column in inspect(model).primary_key
        )
    )


async def count(session: AsyncSession, model: type[Any]) -> int:
    return (await session.scalar(select(func.count()).select_from(model))) or 0


# --------------------------------------------------------------------------- #
# Round-tripping
# --------------------------------------------------------------------------- #


class TestRoundTrip:
    def test_every_table_has_a_seeder(self) -> None:
        """A table with no seeder is a table with no coverage below.

        The enum, constraint and cascade tests are all generated from these
        seeders, so a mapping added without one would be silently skipped by
        every generated test rather than reported as untested.
        """
        assert set(SEEDERS) == {t.name for t in tables()}
        assert set(MODELS) == {t.name for t in tables()}

    async def test_signal(self, db_session: AsyncSession) -> None:
        await seed_signal(db_session)
        row = await reload(db_session, SignalRow, "sig_1")

        assert row.native_id == "t3_1abcde"
        assert row.timestamp == NAIVE_TS
        assert row.content_text.startswith("Our observability bill")
        # Column defaults, which a partially-populated insert relies on: the
        # enrichment stages fill these in later and must not have to.
        assert row.entities == [] and row.embeddings == []
        assert row.engagement == {} and row.signal_metadata == {}
        assert row.language_code == "und"
        assert row.status is SignalStatus.RAW
        assert row.enrichment_attempts == 0

    def test_signal_metadata_column_keeps_its_sql_name(self) -> None:
        """`metadata` is reserved on a Declarative class; the column is not.

        Renaming the attribute to `signal_metadata` was necessary to avoid
        shadowing `Base.metadata`. Letting the *column* follow the rename would
        have silently changed the schema, so the mapping pins it explicitly.
        """
        assert "metadata" in table_named("signals").columns
        assert SignalRow.signal_metadata.key == "signal_metadata"
        assert SignalRow.signal_metadata.expression.name == "metadata"

    async def test_json_columns_round_trip_structure(self, db_session: AsyncSession) -> None:
        """`JSONVariant` is `JSON` here and `JSONB` on PostgreSQL; both must
        return the structure, not a string."""
        await _add(
            db_session,
            make_signal(
                entities=[{"surface": "Datadog", "type": "Company"}],
                engagement={"raw": {"score": 412}},
                signal_metadata={"reddit.awards": {"gold": [1, 2]}},
            ),
        )
        row = await reload(db_session, SignalRow, "sig_1")

        assert row.entities[0]["surface"] == "Datadog"
        assert row.engagement["raw"]["score"] == 412
        assert row.signal_metadata["reddit.awards"]["gold"] == [1, 2]

    async def test_connector_account(self, db_session: AsyncSession) -> None:
        await _add(
            db_session,
            make_connector_account(
                encrypted_credentials=b"gAAAAAB-not-really-fernet",
                credential_updated_at=FETCHED_AT,
            ),
        )
        row = await reload(db_session, ConnectorAccountRow, "acct_1")

        assert row.params["subreddits"] == ["devops", "sre"]
        # `LargeBinary`, so bytes in and bytes out -- a `Text` column here would
        # round-trip through `str` and tolerate a plaintext write.
        assert row.encrypted_credentials == b"gAAAAAB-not-really-fernet"
        assert row.credential_key_version == 1
        assert row.enabled is True
        assert row.deleted_at is None and row.is_deleted is False

    async def test_connector_cursor(self, db_session: AsyncSession) -> None:
        await seed_connector_cursor(db_session)
        row = await reload(db_session, ConnectorCursorRow, "cur_1")

        assert row.cursor == {"page_token": "t3_zzz"}
        assert row.cursor_version == 1
        assert row.watermark == NAIVE_TS

    async def test_investigation(self, db_session: AsyncSession) -> None:
        await seed_investigation(db_session)
        row = await reload(db_session, InvestigationRow, "inv_1")

        assert row.status is InvestigationStatus.QUEUED
        assert row.plan is None, "'not planned yet' must stay distinct from 'planned nothing'"
        assert row.report_id is None
        assert (row.step_count, row.token_input, row.token_output) == (0, 0, 0)

    async def test_investigation_cost_reads_back_as_float(self, db_session: AsyncSession) -> None:
        """`Numeric(asdecimal=False)`: exact in storage, `float` in Python.

        The column is `NUMERIC` because it is summed for billing. `asdecimal=True`
        would make SQLite emit a lossy-conversion `SAWarning` on every read, which
        `pyproject.toml` turns into an error -- so this assertion also guards the
        flag that keeps the unit suite runnable at all.
        """
        await _add(db_session, make_investigation(cost_usd=1.234567))
        row = await reload(db_session, InvestigationRow, "inv_1")

        assert isinstance(row.cost_usd, float)
        assert row.cost_usd == pytest.approx(1.234567, abs=1e-6)

    async def test_investigation_step(self, db_session: AsyncSession) -> None:
        await seed_investigation_step(db_session)
        row = await reload(db_session, InvestigationStepRow, "step_1")

        assert row.sequence == 0
        assert row.agent is AgentName.PLANNER
        assert row.status is StepStatus.PENDING
        assert row.input == {"question": "why?"}
        assert row.output is None, "a running step has no validated output yet"

    async def test_report(self, db_session: AsyncSession) -> None:
        await seed_report(db_session)
        row = await reload(db_session, ReportRow, "rep_1")

        assert row.status is ReportStatus.DRAFT
        assert row.format is ReportFormat.MARKDOWN
        assert row.version == 1
        assert row.object_key is None, "only the R2 key ever lands here, and not until render"
        assert row.superseded_by is None

    async def test_report_section(self, db_session: AsyncSession) -> None:
        await seed_report_section(db_session)
        row = await reload(db_session, ReportSectionRow, "sec_1")

        assert row.ordinal == 0
        assert row.heading == "What changed"
        assert row.confidence == pytest.approx(0.8)

    async def test_citation(self, db_session: AsyncSession) -> None:
        await seed_citation(db_session)
        row = await reload(db_session, CitationRow, "cit_1")

        assert row.signal_id == "sig_1"
        assert row.quote == "our observability bill tripled"
        assert (row.char_start, row.char_end) == (4, 34)
        assert row.relevance == pytest.approx(0.91)

    async def test_citation_signal_id_is_a_soft_reference(self, db_session: AsyncSession) -> None:
        """The soft reference that makes erasure possible.

        A deletion request must be able to hard-delete a Signal. `CASCADE` would
        rewrite a report someone already read; `RESTRICT` would make erasure
        impossible. So the citation keeps its quote and dangles, and the Critic
        reports `broken_citation` -- which only works if no FK is declared here.
        """
        assert not table_named("citations").columns["signal_id"].foreign_keys

        await seed_report_section(db_session)
        await _add(db_session, make_citation(signal_id="sig_never_existed"))
        row = await reload(db_session, CitationRow, "cit_1")
        assert row.signal_id == "sig_never_existed"

    async def test_agent_run(self, db_session: AsyncSession) -> None:
        await seed_agent_run(db_session)
        row = await reload(db_session, AgentRunRow, "run_1")

        assert row.model == "claude-sonnet-5"
        assert (row.prompt_id, row.prompt_version) == ("retriever.hybrid", "v1")
        assert row.status is RunStatus.OK
        assert row.cached_tokens == 0
        assert row.started_at == NAIVE_TS

    async def test_trace(self, db_session: AsyncSession) -> None:
        await seed_trace(db_session)
        row = await reload(db_session, TraceRow, "trc_1")

        assert (row.trace_id, row.span_id) == ("a" * 32, "b" * 16)
        assert row.attributes == {"k": 20}


# --------------------------------------------------------------------------- #
# Enum columns (`TolerantEnumType`)
# --------------------------------------------------------------------------- #


def enum_columns() -> list[tuple[str, str]]:
    """Every `TolerantEnumType` column, derived from the metadata.

    Generated rather than listed so a new enum column is covered the moment it is
    mapped. That matters here more than elsewhere: the whole point of
    `TolerantEnumType` is behaviour on read, which nothing else exercises.
    """
    return sorted(
        (table.name, column.name)
        for table in tables()
        for column in table.columns
        if isinstance(column.type, TolerantEnumType)
    )


def enum_class_of(table_name: str, column_name: str) -> type[Any]:
    column_type = table_named(table_name).columns[column_name].type
    assert isinstance(column_type, TolerantEnumType)
    return column_type.enum_cls


class TestEnumColumns:
    def test_the_expected_columns_are_tolerant(self) -> None:
        """Pinned so that swapping one for `sqlalchemy.Enum` is a failing test.

        A native PostgreSQL enum or `Enum(native_enum=False)` constrains the
        column, which would make adding a `Platform` member require a migration
        before a single row could be written -- exactly the coordinated deploy
        `TolerantStrEnum` exists to avoid.
        """
        assert enum_columns() == [
            ("agent_runs", "agent"),
            ("agent_runs", "status"),
            ("artifacts", "kind"),
            ("artifacts", "outcome"),
            ("artifacts", "platform"),
            ("artifacts", "state"),
            ("connector_accounts", "auth_type"),
            ("connector_accounts", "platform"),
            ("connector_accounts", "status"),
            ("feature_links", "method"),
            ("features", "state"),
            ("identity_links", "method"),
            ("identity_links", "platform"),
            ("investigation_steps", "agent"),
            ("investigation_steps", "status"),
            ("investigations", "status"),
            ("people", "platform"),
            ("reports", "format"),
            ("reports", "status"),
            ("signals", "platform"),
            ("signals", "source"),
            ("signals", "status"),
            ("sources", "platform"),
            ("sources", "watch_status"),
            ("versions", "state"),
        ]

    def test_stored_as_plain_varchar_without_a_constraint(self) -> None:
        """No `CREATE TYPE`, and no `CHECK` enumerating the members either.

        Either one would mean a new `Platform` cannot be written until a
        migration has run everywhere -- the coordinated deploy the tolerant enum
        exists to avoid. A `CHECK ... IN (...)` is the version of that mistake
        which looks portable and therefore harmless.
        """
        for table_name, column_name in enum_columns():
            column = table_named(table_name).columns[column_name]
            assert isinstance(column.type.impl_instance, String)

        for table in tables():
            for constraint in table.constraints:
                if isinstance(constraint, CheckConstraint):
                    assert " IN (" not in str(constraint.sqltext).upper()

    @pytest.mark.parametrize(("table_name", "column_name"), enum_columns())
    async def test_reads_back_as_an_enum_member(
        self, db_session: AsyncSession, table_name: str, column_name: str
    ) -> None:
        """Not a bare `str`.

        `TolerantStrEnum` members compare equal to their value, so `== "reddit"`
        would pass either way; identity against the member is what actually
        distinguishes a decoded column from an undecoded one, and callers do
        `is Platform.REDDIT` and `.is_retrievable` on these.
        """
        row = await SEEDERS[table_name](db_session)
        reloaded = await reload_row(db_session, row)
        value = getattr(reloaded, column_name)

        assert isinstance(value, enum_class_of(table_name, column_name))

    @pytest.mark.parametrize(("table_name", "column_name"), enum_columns())
    async def test_value_from_a_newer_writer_degrades_or_raises(
        self, db_session: AsyncSession, table_name: str, column_name: str
    ) -> None:
        """The behaviour the column type exists for, asserted per column.

        A tolerant vocabulary degrades an unrecognized member to `UNKNOWN`
        exactly as it does over Kafka, so a reader on older code survives a
        rolling deploy. A closed one -- `SignalStatus`, owned entirely by the
        pipeline -- must instead raise, because an unrecognized value there is a
        bug rather than version skew. Which of the two applies is read off the
        enum, so the test follows the vocabulary rather than a hardcoded list.
        """
        enum_cls = enum_class_of(table_name, column_name)
        row = await SEEDERS[table_name](db_session)
        await db_session.execute(
            text(f"UPDATE {table_name} SET {column_name} = :v").bindparams(
                v="member_from_a_newer_build"
            )
        )
        await db_session.commit()

        if "UNKNOWN" in enum_cls.__members__:
            reloaded = await reload_row(db_session, row)
            assert getattr(reloaded, column_name) is enum_cls.UNKNOWN
        else:
            with pytest.raises(ValueError, match="is not a valid"):
                await reload_row(db_session, row)

    def test_signal_status_is_the_closed_one(self) -> None:
        """Guards the branch above: if `SignalStatus` ever gains `UNKNOWN`, the
        parametrized test silently stops asserting that anything fails loudly."""
        assert "UNKNOWN" not in SignalStatus.__members__

    async def test_case_insensitive_value_still_resolves(self, db_session: AsyncSession) -> None:
        """Providers are inconsistent about casing; `REDDIT` is not unknown."""
        await seed_signal(db_session)
        await db_session.execute(text("UPDATE signals SET platform = 'REDDIT'"))
        await db_session.commit()

        assert (await reload(db_session, SignalRow, "sig_1")).platform is Platform.REDDIT

    async def test_writes_the_value_not_the_repr(self, db_session: AsyncSession) -> None:
        """`Platform.REDDIT` must land as `reddit`, so that a hand-written SQL
        report or an Alembic data migration reads the same values the pipeline
        does."""
        await seed_signal(db_session)
        stored = await db_session.scalar(text("SELECT platform FROM signals WHERE id = 'sig_1'"))

        assert stored == "reddit"


# --------------------------------------------------------------------------- #
# CHECK constraints
# --------------------------------------------------------------------------- #


async def _violate_supersede_self(session: AsyncSession) -> None:
    # Mutated after insert rather than inserted self-referencing, so that the
    # self-referencing foreign key on `superseded_by` is satisfied and the CHECK
    # is unambiguously what rejects the row. `autoflush=False` keeps the UPDATE
    # pending until the test commits.
    report = await seed_report(session)
    report.superseded_by = report.id


async def _violate_duplicate_self(session: AsyncSession) -> None:
    session.add(make_signal(id="sig_dup", status=SignalStatus.DUPLICATE, duplicate_of="sig_dup"))


CHECK_VIOLATIONS: list[tuple[str, Callable[[AsyncSession], Awaitable[None]]]] = [
    # -- signals -----------------------------------------------------------
    ("ck_signals_confidence_range", lambda s: _add_only(s, make_signal(confidence=1.5))),
    (
        "ck_signals_language_confidence_range",
        lambda s: _add_only(s, make_signal(language_confidence=-0.1)),
    ),
    (
        "ck_signals_char_count_non_negative",
        lambda s: _add_only(s, make_signal(content_char_count=-1)),
    ),
    (
        "ck_signals_duplicate_points_elsewhere",
        lambda s: _add_only(s, make_signal(status=SignalStatus.DUPLICATE)),
    ),
    ("ck_signals_duplicate_points_elsewhere", _violate_duplicate_self),
    # -- connector_accounts -------------------------------------------------
    (
        "ck_connector_accounts_sync_interval_positive",
        lambda s: _add_only(s, make_connector_account(sync_interval_seconds=0)),
    ),
    (
        "ck_connector_accounts_failures_non_negative",
        lambda s: _add_only(s, make_connector_account(consecutive_failures=-1)),
    ),
    (
        "ck_connector_accounts_key_version_positive",
        lambda s: _add_only(s, make_connector_account(credential_key_version=0)),
    ),
    (
        "ck_connector_accounts_credential_has_timestamp",
        lambda s: _add_only(s, make_connector_account(encrypted_credentials=b"cipher")),
    ),
    (
        "ck_connector_accounts_disabled_implies_not_enabled",
        lambda s: _add_only(
            s,
            make_connector_account(status=ConnectorAccountStatus.DISABLED, enabled=True),
        ),
    ),
    # -- connector_cursors --------------------------------------------------
    (
        "ck_connector_cursors_cursor_version_positive",
        lambda s: _seed_then(s, seed_connector_account, make_connector_cursor(cursor_version=0)),
    ),
    # -- investigations -----------------------------------------------------
    (
        "ck_investigations_step_count_non_negative",
        lambda s: _add_only(s, make_investigation(step_count=-1)),
    ),
    (
        "ck_investigations_token_input_non_negative",
        lambda s: _add_only(s, make_investigation(token_input=-1)),
    ),
    (
        "ck_investigations_token_output_non_negative",
        lambda s: _add_only(s, make_investigation(token_output=-1)),
    ),
    (
        "ck_investigations_cost_non_negative",
        lambda s: _add_only(s, make_investigation(cost_usd=-0.01)),
    ),
    (
        "ck_investigations_completed_after_started",
        lambda s: _add_only(s, make_investigation(completed_at=FETCHED_AT)),
    ),
    (
        "ck_investigations_completed_after_started",
        lambda s: _add_only(s, make_investigation(started_at=FETCHED_AT, completed_at=TS)),
    ),
    # -- investigation_steps ------------------------------------------------
    (
        "ck_investigation_steps_sequence_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_investigation_step(sequence=-1)),
    ),
    (
        "ck_investigation_steps_duration_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_investigation_step(duration_ms=-1)),
    ),
    (
        "ck_investigation_steps_token_input_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_investigation_step(token_input=-1)),
    ),
    (
        "ck_investigation_steps_token_output_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_investigation_step(token_output=-1)),
    ),
    # -- reports ------------------------------------------------------------
    (
        "ck_reports_confidence_range",
        lambda s: _seed_then(s, seed_investigation, make_report(confidence=1.5)),
    ),
    (
        "ck_reports_version_positive",
        lambda s: _seed_then(s, seed_investigation, make_report(version=0)),
    ),
    ("ck_reports_supersede_points_elsewhere", _violate_supersede_self),
    # -- report_sections ----------------------------------------------------
    (
        "ck_report_sections_ordinal_non_negative",
        lambda s: _seed_then(s, seed_report, make_report_section(ordinal=-1)),
    ),
    (
        "ck_report_sections_confidence_range",
        lambda s: _seed_then(s, seed_report, make_report_section(confidence=-0.1)),
    ),
    # -- citations ----------------------------------------------------------
    (
        "ck_citations_char_start_non_negative",
        lambda s: _seed_then(s, seed_report_section, make_citation(char_start=-1)),
    ),
    (
        "ck_citations_char_range_ordered",
        lambda s: _seed_then(s, seed_report_section, make_citation(char_start=34, char_end=4)),
    ),
    (
        "ck_citations_relevance_range",
        lambda s: _seed_then(s, seed_report_section, make_citation(relevance=1.5)),
    ),
    # -- agent_runs ---------------------------------------------------------
    (
        "ck_agent_runs_input_tokens_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_agent_run(input_tokens=-1)),
    ),
    (
        "ck_agent_runs_output_tokens_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_agent_run(output_tokens=-1)),
    ),
    (
        "ck_agent_runs_cached_tokens_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_agent_run(cached_tokens=-1)),
    ),
    (
        "ck_agent_runs_cost_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_agent_run(cost_usd=-0.01)),
    ),
    (
        "ck_agent_runs_latency_non_negative",
        lambda s: _seed_then(s, seed_investigation, make_agent_run(latency_ms=-1)),
    ),
    # -- traces -------------------------------------------------------------
    (
        "ck_traces_trace_id_length",
        lambda s: _seed_then(s, seed_agent_run, make_trace(trace_id="a" * 31)),
    ),
    (
        "ck_traces_span_id_length",
        lambda s: _seed_then(s, seed_agent_run, make_trace(span_id="b" * 15)),
    ),
    (
        "ck_traces_parent_span_id_length",
        lambda s: _seed_then(s, seed_agent_run, make_trace(parent_span_id="c" * 15)),
    ),
    (
        "ck_traces_parent_is_not_self",
        lambda s: _seed_then(s, seed_agent_run, make_trace(parent_span_id="b" * 16)),
    ),
]


async def _add_only(session: AsyncSession, row: Any) -> None:
    """Stage a row without committing -- the test commits and expects the raise."""
    session.add(row)


async def _seed_then(
    session: AsyncSession,
    seeder: Callable[[AsyncSession], Awaitable[Any]],
    row: Any,
) -> None:
    """Insert the parents a foreign key needs, then stage the offending row."""
    await seeder(session)
    session.add(row)


class TestCheckConstraints:
    @pytest.mark.parametrize(
        ("constraint_name", "prepare"),
        CHECK_VIOLATIONS,
        ids=[f"{i}-{name}" for i, (name, _) in enumerate(CHECK_VIOLATIONS)],
    )
    async def test_rejects_the_value_it_names(
        self,
        db_session: AsyncSession,
        constraint_name: str,
        prepare: Callable[[AsyncSession], Awaitable[None]],
    ) -> None:
        """Each CHECK is fed exactly the value it was written to refuse.

        The constraint *name* is asserted, not just "something failed": several
        of these tables carry five or six checks, and a row that violates two at
        once would otherwise let a broken constraint hide behind a working one.
        """
        await prepare(db_session)

        with pytest.raises(IntegrityError) as excinfo:
            await db_session.commit()

        assert constraint_name in str(excinfo.value.orig)

    def test_every_check_constraint_is_exercised(self) -> None:
        """A CHECK nobody tests is a CHECK nobody knows is inverted.

        Reversing a comparison in one of these expressions is invisible -- the
        migration applies, the table accepts every row it accepted before, and
        the constraint simply stops rejecting anything.
        """
        declared = {
            constraint.name
            for table in tables()
            for constraint in table.constraints
            if isinstance(constraint, CheckConstraint)
        }
        assert declared == {name for name, _ in CHECK_VIOLATIONS}


# --------------------------------------------------------------------------- #
# UNIQUE constraints
# --------------------------------------------------------------------------- #


class TestUniqueConstraints:
    async def test_signals_one_row_per_source_item(self, db_session: AsyncSession) -> None:
        """The derived `Signal.id` already guarantees this; the constraint makes
        it true at the storage layer, where a backfill script also lives."""
        await seed_signal(db_session)
        db_session.add(make_signal(id="sig_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_connector_cursors_one_watermark_per_key(self, db_session: AsyncSession) -> None:
        """`(connector_slug, account_id, params_hash)` from `connector-spec` §4.

        A second cursor row for one key halves the effective watermark: two
        runners advance different rows and each starts from the other's stale
        position.
        """
        await seed_connector_cursor(db_session)
        db_session.add(make_connector_cursor(id="cur_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_investigation_steps_one_row_per_slot(self, db_session: AsyncSession) -> None:
        await seed_investigation_step(db_session)
        db_session.add(make_investigation_step(id="step_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_investigation_steps_allow_a_reordered_rerun(
        self, db_session: AsyncSession
    ) -> None:
        """The Critic loop re-runs an agent, so `agent` repeats within an
        investigation; only `sequence` has to stay unique."""
        await seed_investigation_step(db_session)
        await _add(
            db_session, make_investigation_step(id="step_2", sequence=1, agent=AgentName.PLANNER)
        )

        assert await count(db_session, InvestigationStepRow) == 2

    async def test_reports_one_row_per_version(self, db_session: AsyncSession) -> None:
        """Two rows claiming version 2 make `?version=2` ambiguous."""
        await seed_report(db_session)
        db_session.add(make_report(id="rep_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_report_sections_one_row_per_ordinal(self, db_session: AsyncSession) -> None:
        await seed_report_section(db_session)
        db_session.add(make_report_section(id="sec_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_traces_span_is_unique_within_its_trace(self, db_session: AsyncSession) -> None:
        """An at-least-once exporter retries batches; re-ingesting one must be
        idempotent rather than duplicating every span."""
        await seed_trace(db_session)
        db_session.add(make_trace(id="trc_2"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_connector_accounts_reject_a_second_live_config(
        self, db_session: AsyncSession
    ) -> None:
        """Two live accounts on one config double-fetch and then fight over a
        cursor key."""
        await seed_connector_account(db_session)
        db_session.add(make_connector_account(id="acct_2", display_name="duplicate"))

        with pytest.raises(IntegrityError, match="UNIQUE constraint failed"):
            await db_session.commit()

    async def test_connector_accounts_free_the_key_when_tombstoned(
        self, db_session: AsyncSession
    ) -> None:
        """Why it is a partial index and not a `UniqueConstraint`.

        With `SoftDeleteMixin`, a plain unique constraint would let a deleted
        account hold its configuration hostage forever -- re-creating it would
        fail against a row the operator can no longer see.
        """
        account = await seed_connector_account(db_session)
        account.deleted_at = FETCHED_AT
        await db_session.commit()

        await _add(db_session, make_connector_account(id="acct_2", display_name="recreated"))

        assert await count(db_session, ConnectorAccountRow) == 2

    def test_every_uniqueness_rule_is_exercised(self) -> None:
        """Includes the partial unique *index*, which is a uniqueness rule that
        does not appear in `table.constraints` and is therefore easy to miss."""
        declared_constraints = {
            constraint.name
            for table in tables()
            for constraint in table.constraints
            if isinstance(constraint, UniqueConstraint)
        }
        declared_indexes = {
            index.name for table in tables() for index in table.indexes if index.unique
        }
        assert declared_constraints == {
            "uq_signals_platform_native_id",
            "uq_artifacts_platform_native_id",
            "uq_sources_platform_external_id",
            "uq_people_platform_external_id",
            "uq_projects_tenant_id_slug",
            # A project may not hold two versions called `v1`, nor two features
            # called `image upload` -- both would make the deterministic id
            # collide with a row that is not the same thing.
            "uq_versions_project_id_name",
            "uq_features_project_id_name",
            "uq_connector_cursors_connector_slug_account_id_params_hash",
            "uq_investigation_steps_investigation_id_sequence",
            "uq_reports_investigation_id_version",
            "uq_report_sections_report_id_ordinal",
            "uq_traces_trace_id_span_id",
        }
        assert declared_indexes == {"uq_connector_accounts_live_config"}


# --------------------------------------------------------------------------- #
# Foreign keys
# --------------------------------------------------------------------------- #


EXPECTED_ON_DELETE: dict[str, str] = {
    # A link asserts that an account belongs to a human. Delete either end and
    # the assertion is about something that no longer exists, so it goes too --
    # unlike an artifact, a link holds no history of its own to protect.
    "fk_identity_links_identity_id_identities": "CASCADE",
    "fk_identity_links_person_id_people": "CASCADE",
    # A membership claim says an artifact is part of a feature. Delete either and
    # the claim is about something that no longer exists.
    "fk_feature_links_feature_id_features": "CASCADE",
    "fk_feature_links_artifact_id_artifacts": "CASCADE",
    # Cancelling a release does not mean the work never happened, so the features
    # survive and simply stop belonging to a version.
    "fk_features_version_id_versions": "SET NULL",
    # Same reasoning as artifacts and their source: deleting a project that still
    # holds work is a decision to be made explicitly, not a side effect.
    "fk_features_project_id_projects": "RESTRICT",
    "fk_versions_project_id_projects": "RESTRICT",
    # A cursor is derived state; without its account there is nothing to resume.
    "fk_connector_cursors_account_id_connector_accounts": "CASCADE",
    # Deleting a report must not erase the record that the run happened.
    "fk_investigations_report_id_reports": "SET NULL",
    # A step's input and output quote the user's question and retrieved content.
    "fk_investigation_steps_investigation_id_investigations": "CASCADE",
    "fk_reports_investigation_id_investigations": "CASCADE",
    # Cascading backwards through a version chain would delete every older
    # version from a single delete of the newest.
    "fk_reports_superseded_by_reports": "SET NULL",
    "fk_report_sections_report_id_reports": "CASCADE",
    "fk_citations_report_id_reports": "CASCADE",
    "fk_citations_section_id_report_sections": "CASCADE",
    # Money that was spent stays spent; the row holds no user content.
    "fk_agent_runs_investigation_id_investigations": "SET NULL",
    # A span describing a deleted call is unresolvable noise.
    "fk_traces_agent_run_id_agent_runs": "CASCADE",
    # An artifact whose origin is unknown cannot be cited, and a citation is what
    # every claim in this system rests on. Deleting a source is a decision about
    # what happens to its history and has to be made explicitly, not taken as a
    # side effect -- so RESTRICT rather than CASCADE.
    "fk_artifacts_source_id_sources": "RESTRICT",
    # An artifact routinely has no actor at all: a CI run is triggered by a
    # machine. A deleted account must not take the commits it authored with it,
    # so the reference is cleared and the work survives.
    "fk_artifacts_actor_id_people": "SET NULL",
    # Removing a project must not delete the repositories it grouped, still less
    # their history. It un-groups them.
    "fk_sources_project_id_projects": "SET NULL",
}


class TestForeignKeys:
    async def test_the_fixture_actually_enforces_them(self, db_session: AsyncSession) -> None:
        """Guards every other test in this class.

        SQLite ships with `PRAGMA foreign_keys` off, and with it off a
        `REFERENCES` clause is parsed and then ignored -- orphans insert fine and
        parents delete without touching their children. Every cascade assertion
        below would still pass or fail for the wrong reason, so this asserts the
        pragma is on before any of them are believed.
        """
        db_session.add(make_report(investigation_id="inv_does_not_exist"))

        with pytest.raises(IntegrityError, match="FOREIGN KEY constraint failed"):
            await db_session.commit()

    def test_declared_actions_match_the_documented_intent(self) -> None:
        """`CASCADE` and `SET NULL` are not interchangeable here.

        Each choice is argued for in its column docstring, and swapping one is
        both silent and destructive: `CASCADE` on `agent_runs` would let deleting
        an investigation rewrite last month's cost total.
        """
        declared = {
            constraint.name: constraint.ondelete
            for table in tables()
            for constraint in table.constraints
            if isinstance(constraint, ForeignKeyConstraint)
        }
        assert declared == EXPECTED_ON_DELETE

    async def test_deleting_an_account_takes_its_cursors(self, db_session: AsyncSession) -> None:
        await seed_connector_cursor(db_session)
        await db_session.execute(text("DELETE FROM connector_accounts WHERE id = 'acct_1'"))
        await db_session.commit()

        assert await count(db_session, ConnectorCursorRow) == 0

    async def test_tombstoning_an_account_keeps_its_cursors(self, db_session: AsyncSession) -> None:
        """The reason the account is soft-deletable at all: re-enabling it must
        resume from the watermark rather than re-crawl history."""
        await seed_connector_cursor(db_session)
        await db_session.execute(
            text("UPDATE connector_accounts SET deleted_at = :t").bindparams(t=FETCHED_AT)
        )
        await db_session.commit()

        assert await count(db_session, ConnectorCursorRow) == 1

    async def test_deleting_an_investigation_takes_its_steps_and_reports(
        self, db_session: AsyncSession
    ) -> None:
        """An erasure request must reach everything quoting the user."""
        await seed_citation(db_session)
        await _add(db_session, make_investigation_step())
        await db_session.execute(text("DELETE FROM investigations WHERE id = 'inv_1'"))
        await db_session.commit()

        assert await count(db_session, InvestigationStepRow) == 0
        assert await count(db_session, ReportRow) == 0
        assert await count(db_session, ReportSectionRow) == 0
        assert await count(db_session, CitationRow) == 0

    async def test_deleting_an_investigation_keeps_the_cost_record(
        self, db_session: AsyncSession
    ) -> None:
        await seed_agent_run(db_session)
        await db_session.execute(text("DELETE FROM investigations WHERE id = 'inv_1'"))
        await db_session.commit()

        run = await reload(db_session, AgentRunRow, "run_1")
        assert run.investigation_id is None
        assert run.cost_usd == pytest.approx(0.0144)

    async def test_deleting_a_report_detaches_the_investigation(
        self, db_session: AsyncSession
    ) -> None:
        """The cycle `investigations <-> reports` resolves in this direction with
        `SET NULL`, so the record that the run happened survives its output."""
        await seed_report(db_session)
        await db_session.execute(text("UPDATE investigations SET report_id = 'rep_1'"))
        await db_session.commit()

        await db_session.execute(text("DELETE FROM reports WHERE id = 'rep_1'"))
        await db_session.commit()

        assert (await reload(db_session, InvestigationRow, "inv_1")).report_id is None

    async def test_deleting_a_report_takes_its_sections_and_citations(
        self, db_session: AsyncSession
    ) -> None:
        await seed_citation(db_session)
        await db_session.execute(text("DELETE FROM reports WHERE id = 'rep_1'"))
        await db_session.commit()

        assert await count(db_session, ReportSectionRow) == 0
        assert await count(db_session, CitationRow) == 0

    async def test_deleting_a_section_takes_only_its_own_citations(
        self, db_session: AsyncSession
    ) -> None:
        """A citation supporting the report as a whole carries a NULL section and
        must survive a section being rewritten away."""
        await seed_citation(db_session)
        await _add(db_session, make_citation(id="cit_2", section_id=None))

        await db_session.execute(text("DELETE FROM report_sections WHERE id = 'sec_1'"))
        await db_session.commit()

        remaining = await db_session.scalars(select(CitationRow.id))
        assert list(remaining) == ["cit_2"]

    async def test_deleting_a_newer_report_leaves_the_older_one(
        self, db_session: AsyncSession
    ) -> None:
        await seed_report(db_session)
        await _add(db_session, make_report(id="rep_2", version=2))
        await db_session.execute(
            text("UPDATE reports SET superseded_by = 'rep_2' WHERE id = 'rep_1'")
        )
        await db_session.commit()

        await db_session.execute(text("DELETE FROM reports WHERE id = 'rep_2'"))
        await db_session.commit()

        older = await reload(db_session, ReportRow, "rep_1")
        assert older.superseded_by is None

    async def test_deleting_a_run_takes_its_spans(self, db_session: AsyncSession) -> None:
        await seed_trace(db_session)
        await db_session.execute(text("DELETE FROM agent_runs WHERE id = 'run_1'"))
        await db_session.commit()

        assert await count(db_session, TraceRow) == 0

    async def test_a_span_without_a_run_is_legal(self, db_session: AsyncSession) -> None:
        """Most spans are not model calls -- a retrieval fan-out produces spans
        with no run behind them."""
        await _add(db_session, make_trace(agent_run_id=None))

        assert (await reload(db_session, TraceRow, "trc_1")).agent_run_id is None


# --------------------------------------------------------------------------- #
# Mixins
# --------------------------------------------------------------------------- #


class TestTimestampMixin:
    async def test_created_at_comes_from_the_database(self, db_session: AsyncSession) -> None:
        """Not from Python.

        With workers on several hosts, Python-side timestamps skew and
        `ORDER BY created_at` stops being a stable ordering. The assertion that
        the attribute is `None` before the flush is what proves the value was
        produced by the server default rather than by the mapping.
        """
        row = make_investigation()
        assert row.created_at is None

        db_session.add(row)
        await db_session.commit()
        await db_session.refresh(row)

        assert isinstance(row.created_at, datetime)
        assert isinstance(row.updated_at, datetime)

    async def test_updated_at_moves_on_update(self, db_session: AsyncSession) -> None:
        """`onupdate` is SQL, so it fires for writers that never load the object.

        Seeded with a stale value rather than compared against `created_at`:
        SQLite's `CURRENT_TIMESTAMP` has one-second resolution, so a fresh row
        updated immediately would show two identical timestamps and the
        assertion would prove nothing.
        """
        stale = datetime(2000, 1, 1, 0, 0, 0)
        await _add(db_session, make_investigation(created_at=stale, updated_at=stale))

        row = await reload(db_session, InvestigationRow, "inv_1")
        row.query = "reworded question"
        await db_session.commit()
        await db_session.refresh(row)

        assert row.updated_at > stale
        assert row.created_at == stale, "created_at must not be rewritten by an update"

    async def test_a_raw_insert_still_gets_both(self, db_session: AsyncSession) -> None:
        """The case that matters for backfills and `psql`.

        A Python-side `default=` would leave these NULL for any writer that does
        not go through the ORM, and the columns are `NOT NULL`.
        """
        await db_session.execute(
            text(
                "INSERT INTO investigations"
                " (id, query, status, step_count, token_input, token_output, cost_usd)"
                " VALUES ('inv_raw', 'from a migration', 'queued', 0, 0, 0, 0)"
            )
        )
        await db_session.commit()

        row = await reload(db_session, InvestigationRow, "inv_raw")
        assert row.created_at is not None
        assert row.updated_at is not None


class TestTenantMixin:
    async def test_defaults_to_the_single_tenant(self, db_session: AsyncSession) -> None:
        """A literal rather than NULL: a nullable tenant column makes every query
        say `WHERE tenant_id = :t OR tenant_id IS NULL`, and the day that `OR` is
        forgotten is the day one tenant reads another's data."""
        await seed_signal(db_session)

        assert (await reload(db_session, SignalRow, "sig_1")).tenant_id == DEFAULT_TENANT
        assert DEFAULT_TENANT == "default"

    async def test_a_raw_insert_gets_the_server_default(self, db_session: AsyncSession) -> None:
        await db_session.execute(
            text(
                "INSERT INTO investigations"
                " (id, query, status, step_count, token_input, token_output, cost_usd)"
                " VALUES ('inv_raw', 'from a migration', 'queued', 0, 0, 0, 0)"
            )
        )
        await db_session.commit()

        assert (await reload(db_session, InvestigationRow, "inv_raw")).tenant_id == "default"

    def test_every_table_carries_it(self) -> None:
        """Phase 7 multi-tenancy is designed for now precisely so that adding it
        later does not touch the primary key of every table at once."""
        for table in tables():
            assert "tenant_id" in table.columns, f"{table.name} is not tenant-scoped"
            assert not table.columns["tenant_id"].nullable

    def test_is_indexed_everywhere(self) -> None:
        """Every multi-tenant query filters on it first; an unindexed tenant
        column turns each one into a full scan the moment there are two."""
        for table in tables():
            indexed = [
                index
                for index in table.indexes
                if index.columns.keys() and next(iter(index.columns.keys())) == "tenant_id"
            ]
            assert indexed, f"{table.name} has no index leading with tenant_id"


class TestSoftDelete:
    def test_applies_to_exactly_one_table(self) -> None:
        """Soft delete is the exception, not the default.

        `signals`, `investigations` and `reports` all hold text a user can demand
        the erasure of, and a tombstone still carrying that text would defeat the
        request. `connector_accounts` can be tombstoned only because it holds
        ciphertext and no scraped content.
        """
        soft_deletable = {t.name for t in tables() if "deleted_at" in t.columns}
        assert soft_deletable == {"connector_accounts"}

    async def test_is_deleted_reflects_the_column(self, db_session: AsyncSession) -> None:
        account = await seed_connector_account(db_session)
        assert not account.is_deleted

        account.deleted_at = FETCHED_AT
        await db_session.commit()

        assert (await reload(db_session, ConnectorAccountRow, "acct_1")).is_deleted


# --------------------------------------------------------------------------- #
# Structural invariants that protect migrations
# --------------------------------------------------------------------------- #


class TestNamingConvention:
    """Every constraint and index must be named by the convention in
    `models/orm/base.py`.

    Without it, Alembic autogenerates names from PostgreSQL's defaults -- which
    differ between "created by `CREATE TABLE`" and "created by `ALTER TABLE`" --
    and the migration that created a constraint cannot drop it. The failure
    appears on the downgrade path, long after the review that would have caught
    it.
    """

    @staticmethod
    def _named_objects() -> list[tuple[str, Constraint | Index]]:
        out: list[tuple[str, Constraint | Index]] = []
        for table in tables():
            out += [(table.name, c) for c in table.constraints]
            out += [(table.name, i) for i in table.indexes]
        return out

    def test_nothing_is_anonymous(self) -> None:
        for table_name, obj in self._named_objects():
            assert isinstance(obj.name, str) and obj.name, (
                f"{type(obj).__name__} on {table_name} has no name"
            )

    def test_primary_keys(self) -> None:
        for table in tables():
            for constraint in table.constraints:
                if isinstance(constraint, PrimaryKeyConstraint):
                    assert constraint.name == f"pk_{table.name}"

    def test_unique_constraints(self) -> None:
        for table in tables():
            for constraint in table.constraints:
                if isinstance(constraint, UniqueConstraint):
                    names = "_".join(c.name for c in constraint.columns)
                    assert constraint.name == f"uq_{table.name}_{names}"

    def test_foreign_keys(self) -> None:
        for table in tables():
            for constraint in table.constraints:
                if isinstance(constraint, ForeignKeyConstraint):
                    names = "_".join(c.name for c in constraint.columns)
                    referred = constraint.referred_table.name
                    assert constraint.name == f"fk_{table.name}_{names}_{referred}"

    def test_check_constraints_are_explicitly_named(self) -> None:
        """`ck_%(table_name)s_%(constraint_name)s` needs the `name=` argument.

        A `CheckConstraint` without one does not fall back to a default: the
        convention raises `InvalidRequestError` the moment the constraint is
        attached to its table, which is at import. So this assertion cannot fail
        in the ordinary way -- omitting a name breaks collection of the whole
        suite instead. It stays because it is the readable statement of the rule,
        and because it does catch the case the raise cannot: a name that is
        present but does not describe the table it is on.
        """
        for table in tables():
            for constraint in table.constraints:
                if isinstance(constraint, CheckConstraint):
                    assert constraint.name is not None
                    prefix = f"ck_{table.name}_"
                    assert constraint.name.startswith(prefix)
                    assert len(constraint.name) > len(prefix)

    def test_indexes(self) -> None:
        for table in tables():
            for index in table.indexes:
                assert index.name is not None
                expected_prefix = "uq_" if index.unique else "ix_"
                assert index.name.startswith(expected_prefix)
                assert table.name in index.name

    def test_names_are_unique_across_the_schema(self) -> None:
        """PostgreSQL puts indexes -- including those backing PRIMARY KEY and
        UNIQUE -- in one per-schema namespace, so two tables cannot reuse a name
        even though the constraint would be per-table."""
        names = [obj.name for _, obj in self._named_objects()]
        duplicates = {name for name in names if names.count(name) > 1}
        assert not duplicates


# --------------------------------------------------------------------------- #
# What PostgreSQL must never hold (`docs/data-stores.md` §3.1)
# --------------------------------------------------------------------------- #


VECTOR_TOKENS = frozenset({"vector", "vectors", "embedding", "embeddings"})
RAW_BODY_TOKENS = frozenset({"raw", "payload", "body", "html", "blob", "bytes", "binary"})
SECRET_PATTERN = re.compile(
    r"credential|secret|password|passphrase|api_key|private_key|plaintext|bearer"
)

VECTOR_EXEMPT: dict[tuple[str, str], str] = {
    ("signals", "embeddings"): (
        "EmbeddingRef records -- model, dimensions, collection, point id. The "
        "floats live in Qdrant; these refs are what makes a model migration "
        "tractable."
    ),
    ("signals", "indexed_vector_at"): (
        "A timestamp recording that Qdrant was written, not what was written."
    ),
}

RAW_BODY_EXEMPT: dict[tuple[str, str], str] = {
    ("artifacts", "body"): (
        "A commit message, a pull request description, a Slack message. Bounded "
        "prose the platform's API returns as a field -- not a scraped document. "
        "It is also the text every 'why did we decide X' answer quotes, so it "
        "has to be queryable here rather than behind an object-store fetch."
    ),
    ("signals", "raw_object_key"): "The R2 key. A pointer, not the bytes.",
    ("signals", "raw_sha256"): "Digest of the R2 object, for integrity checks.",
    ("signals", "author_payload"): (
        "The residual Author fields -- bounded metadata from the item envelope, not the item body."
    ),
    ("report_sections", "body"): (
        "Narrative this system generated, queried by attribute and rewritten by "
        "the Critic. R2 holds immutable content-addressed objects, which this is "
        "not."
    ),
}

SECRET_EXEMPT: dict[tuple[str, str], str] = {
    ("connector_accounts", "encrypted_credentials"): "Fernet ciphertext, never plaintext.",
    ("connector_accounts", "credential_key_version"): (
        "Which key generation opens the ciphertext -- required for rotation."
    ),
    ("connector_accounts", "credential_updated_at"): (
        "Drives the 90-day rotation reminder; the only credential fact the API may expose."
    ),
}


def columns() -> list[tuple[str, str, Any]]:
    return [(t.name, c.name, c) for t in tables() for c in t.columns]


class TestForbiddenColumns:
    """`docs/data-stores.md` §3.1: no payload bodies, no vectors, no plaintext
    secrets.

    The exemption tables above are the point of these tests, not a loophole in
    them. Each one names a column and says why it is not the thing it looks like.
    A new column matching any of these patterns fails until somebody writes that
    sentence -- which is exactly the review the two-tier rule needs, and exactly
    the review that does not happen when the only record is a paragraph in a
    design document.
    """

    def test_no_column_holds_an_embedding_vector(self) -> None:
        """Vectors belong in Qdrant. A float array here would make PostgreSQL
        the only place they live and break the rebuild guarantee in both
        directions -- the vectors could not be regenerated from it, and it could
        not be dumped without them."""
        for table_name, column_name, _ in columns():
            tokens = set(column_name.lower().split("_"))
            if tokens & VECTOR_TOKENS:
                assert (table_name, column_name) in VECTOR_EXEMPT, (
                    f"{table_name}.{column_name} looks like a vector column"
                )

    def test_no_column_can_structurally_hold_a_float_array(self) -> None:
        """The teeth behind the name check: `ARRAY(Float)` or a `vector` type
        would pass any naming rule while storing the embeddings outright."""
        for table_name, column_name, column in columns():
            assert not isinstance(column.type, ARRAY), f"{table_name}.{column_name} is an ARRAY"
            type_name = type(column.type).__name__.upper()
            assert "VECTOR" not in type_name, f"{table_name}.{column_name} is {type_name}"

    def test_no_column_holds_a_raw_payload_body(self) -> None:
        """A `TEXT` column of scraped HTML turns the write-ahead log into a
        bandwidth problem, and replicates the bytes to every standby."""
        for table_name, column_name, _ in columns():
            tokens = set(column_name.lower().split("_"))
            if tokens & RAW_BODY_TOKENS:
                assert (table_name, column_name) in RAW_BODY_EXEMPT, (
                    f"{table_name}.{column_name} looks like a raw payload column"
                )

    def test_binary_columns_are_limited_to_ciphertext(self) -> None:
        """`BYTEA` is how raw bytes would arrive if they ever did. There is
        exactly one, it holds Fernet ciphertext, and it is nullable because an
        account legitimately exists without a usable credential."""
        binary = [
            (table_name, column_name)
            for table_name, column_name, column in columns()
            if isinstance(column.type, LargeBinary)
        ]
        assert binary == [("connector_accounts", "encrypted_credentials")]

    def test_no_column_holds_a_plaintext_credential(self) -> None:
        """Third-party secrets exist in PostgreSQL only as ciphertext."""
        for table_name, column_name, _ in columns():
            if SECRET_PATTERN.search(column_name.lower()):
                assert (table_name, column_name) in SECRET_EXEMPT, (
                    f"{table_name}.{column_name} looks like a credential column"
                )

    def test_the_credential_column_is_binary_not_text(self) -> None:
        """A base64 `TEXT` column invites a `SELECT` during a debugging session
        and silently tolerates a plaintext write. `BYTEA` does neither."""
        column = table_named("connector_accounts").columns["encrypted_credentials"]

        assert isinstance(column.type, LargeBinary)
        assert column.nullable

    def test_signals_holds_no_entity_graph(self) -> None:
        """Neo4j owns the edges. `signals.entities` is the mention list the
        graph writer consumes, not the graph itself -- if an agent could learn
        something from one store that is not derivable from PostgreSQL plus R2,
        the rebuild guarantee is already broken."""
        signal_columns = set(table_named("signals").columns.keys())

        assert not {"edges", "relationships", "graph"} & signal_columns
