"""artifacts sources people

Revision ID: 62400f12b918
Revises: 0001
Created: 2026-08-11 17:43:18.539729
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '62400f12b918'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('person_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_people_platform_external_id'),
    schema='omnisense'
    )
    op.create_index(op.f('ix_omnisense_people_platform'), 'people', ['platform'], unique=False, schema='omnisense')
    op.create_index(op.f('ix_omnisense_people_tenant_id'), 'people', ['tenant_id'], unique=False, schema='omnisense')
    op.create_index('ix_people_tenant_platform_handle', 'people', ['tenant_id', 'platform', 'handle'], unique=False, schema='omnisense')
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_sources_platform_external_id'),
    schema='omnisense'
    )
    op.create_index(op.f('ix_omnisense_sources_platform'), 'sources', ['platform'], unique=False, schema='omnisense')
    op.create_index(op.f('ix_omnisense_sources_tenant_id'), 'sources', ['tenant_id'], unique=False, schema='omnisense')
    op.create_index('ix_sources_tenant_platform_name', 'sources', ['tenant_id', 'platform', 'name'], unique=False, schema='omnisense')
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('native_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('artifact_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['omnisense.people.id'], name=op.f('fk_artifacts_actor_id_people'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['omnisense.sources.id'], name=op.f('fk_artifacts_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('platform', 'native_id', name='uq_artifacts_platform_native_id'),
    schema='omnisense'
    )
    op.create_index('ix_artifacts_source_updated', 'artifacts', ['source_id', 'updated_at_source'], unique=False, schema='omnisense')
    op.create_index('ix_artifacts_tenant_actor_time', 'artifacts', ['tenant_id', 'actor_id', sa.literal_column('occurred_at DESC')], unique=False, schema='omnisense')
    op.create_index('ix_artifacts_tenant_failed', 'artifacts', ['tenant_id', 'outcome', sa.literal_column('occurred_at DESC')], unique=False, schema='omnisense', postgresql_where=sa.text("outcome IN ('failure', 'timed_out', 'cancelled')"))
    op.create_index('ix_artifacts_tenant_kind_time', 'artifacts', ['tenant_id', 'kind', sa.literal_column('occurred_at DESC')], unique=False, schema='omnisense')
    op.create_index('ix_artifacts_tenant_open', 'artifacts', ['tenant_id', 'state'], unique=False, schema='omnisense', postgresql_where=sa.text("state IN ('open', 'draft', 'running', 'queued')"))
    op.create_index('ix_artifacts_tenant_source_time', 'artifacts', ['tenant_id', 'source_id', sa.literal_column('occurred_at DESC')], unique=False, schema='omnisense')
    op.create_index(op.f('ix_omnisense_artifacts_kind'), 'artifacts', ['kind'], unique=False, schema='omnisense')
    op.create_index(op.f('ix_omnisense_artifacts_tenant_id'), 'artifacts', ['tenant_id'], unique=False, schema='omnisense')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_omnisense_artifacts_tenant_id'), table_name='artifacts', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_artifacts_kind'), table_name='artifacts', schema='omnisense')
    op.drop_index('ix_artifacts_tenant_source_time', table_name='artifacts', schema='omnisense')
    op.drop_index('ix_artifacts_tenant_open', table_name='artifacts', schema='omnisense', postgresql_where=sa.text("state IN ('open', 'draft', 'running', 'queued')"))
    op.drop_index('ix_artifacts_tenant_kind_time', table_name='artifacts', schema='omnisense')
    op.drop_index('ix_artifacts_tenant_failed', table_name='artifacts', schema='omnisense', postgresql_where=sa.text("outcome IN ('failure', 'timed_out', 'cancelled')"))
    op.drop_index('ix_artifacts_tenant_actor_time', table_name='artifacts', schema='omnisense')
    op.drop_index('ix_artifacts_source_updated', table_name='artifacts', schema='omnisense')
    op.drop_table('artifacts', schema='omnisense')
    op.drop_index('ix_sources_tenant_platform_name', table_name='sources', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_sources_tenant_id'), table_name='sources', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_sources_platform'), table_name='sources', schema='omnisense')
    op.drop_table('sources', schema='omnisense')
    op.drop_index('ix_people_tenant_platform_handle', table_name='people', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_people_tenant_id'), table_name='people', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_people_platform'), table_name='people', schema='omnisense')
    op.drop_table('people', schema='omnisense')
    # ### end Alembic commands ###
