"""identities and identity links

Revision ID: d24586eb2e01
Revises: f96e7fdb00cc
Created: 2026-08-12 11:13:10.440600
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d24586eb2e01"
down_revision: str | None = "f96e7fdb00cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("primary_email", sa.String(length=512), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column(
            "identity_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identities")),
        schema="omnisense",
    )
    op.create_index(
        "ix_identities_tenant_display_name",
        "identities",
        ["tenant_id", "display_name"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_identities_tenant_id"),
        "identities",
        ["tenant_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_table(
        "identity_links",
        sa.Column("person_id", sa.String(length=64), nullable=False),
        sa.Column("identity_id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=256), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["identity_id"],
            ["omnisense.identities.id"],
            name=op.f("fk_identity_links_identity_id_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["omnisense.people.id"],
            name=op.f("fk_identity_links_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", name=op.f("pk_identity_links")),
        schema="omnisense",
    )
    op.create_index(
        "ix_identity_links_tenant_identity_id",
        "identity_links",
        ["tenant_id", "identity_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_identity_links_identity_id"),
        "identity_links",
        ["identity_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_identity_links_method"),
        "identity_links",
        ["method"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_identity_links_tenant_id"),
        "identity_links",
        ["tenant_id"],
        unique=False,
        schema="omnisense",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_omnisense_identity_links_tenant_id"),
        table_name="identity_links",
        schema="omnisense",
    )
    op.drop_index(
        op.f("ix_omnisense_identity_links_method"), table_name="identity_links", schema="omnisense"
    )
    op.drop_index(
        op.f("ix_omnisense_identity_links_identity_id"),
        table_name="identity_links",
        schema="omnisense",
    )
    op.drop_index(
        "ix_identity_links_tenant_identity_id", table_name="identity_links", schema="omnisense"
    )
    op.drop_table("identity_links", schema="omnisense")
    op.drop_index(
        op.f("ix_omnisense_identities_tenant_id"), table_name="identities", schema="omnisense"
    )
    op.drop_index("ix_identities_tenant_display_name", table_name="identities", schema="omnisense")
    op.drop_table("identities", schema="omnisense")
    # ### end Alembic commands ###
