"""projects

Revision ID: f96e7fdb00cc
Revises: 62400f12b918
Created: 2026-08-11 18:05:26.261739
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f96e7fdb00cc'
down_revision: str | None = '62400f12b918'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), 'postgresql'), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_projects_tenant_id_slug'),
    schema='omnisense'
    )
    op.create_index(op.f('ix_omnisense_projects_tenant_id'), 'projects', ['tenant_id'], unique=False, schema='omnisense')
    op.add_column(
        'sources', sa.Column('project_id', sa.String(length=64), nullable=True),
        schema='omnisense',
    )
    op.create_foreign_key(
        op.f('fk_sources_project_id_projects'), 'sources', 'projects',
        ['project_id'], ['id'],
        source_schema='omnisense', referent_schema='omnisense', ondelete='SET NULL',
    )
    op.create_index(
        'ix_sources_tenant_project_id', 'sources', ['tenant_id', 'project_id'],
        unique=False, schema='omnisense',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode again, mirroring upgrade(). Dropping a constraint is as
    # unsupported on SQLite as adding one, and a downgrade that cannot run is a
    # migration that cannot be rolled back off a bad deploy.
    op.drop_constraint(
        op.f('fk_sources_project_id_projects'), 'sources',
        schema='omnisense', type_='foreignkey',
    )
    op.drop_index('ix_sources_tenant_project_id', table_name='sources', schema='omnisense')
    op.drop_column('sources', 'project_id', schema='omnisense')
    op.drop_index(op.f('ix_omnisense_projects_tenant_id'), table_name='projects', schema='omnisense')
    op.drop_table('projects', schema='omnisense')
    # ### end Alembic commands ###
