"""watch status on sources

Revision ID: 135be8e52248
Revises: 58a2968b4294
Created: 2026-08-13 23:46:06.175156
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "135be8e52248"
down_revision: str | None = "58a2968b4294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column("watch_status", sa.String(length=32), server_default="included", nullable=False),
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_sources_watch_status"),
        "sources",
        ["watch_status"],
        unique=False,
        schema="omnisense",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_omnisense_sources_watch_status"), table_name="sources", schema="omnisense"
    )
    op.drop_column("sources", "watch_status", schema="omnisense")
    # ### end Alembic commands ###
