"""versions features and membership

Revision ID: 58a2968b4294
Revises: d24586eb2e01
Created: 2026-08-12 12:04:25.783366
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "58a2968b4294"
down_revision: str | None = "d24586eb2e01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "version_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["omnisense.projects.id"],
            name=op.f("fk_versions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_versions")),
        sa.UniqueConstraint("project_id", "name", name="uq_versions_project_id_name"),
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_versions_project_id"),
        "versions",
        ["project_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_versions_tenant_id"),
        "versions",
        ["tenant_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        "ix_versions_tenant_project_id_state",
        "versions",
        ["tenant_id", "project_id", "state"],
        unique=False,
        schema="omnisense",
    )
    op.create_table(
        "features",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "keywords",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "feature_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.String()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["omnisense.projects.id"],
            name=op.f("fk_features_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["omnisense.versions.id"],
            name=op.f("fk_features_version_id_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_features")),
        sa.UniqueConstraint("project_id", "name", name="uq_features_project_id_name"),
        schema="omnisense",
    )
    op.create_index(
        "ix_features_tenant_project_id_state",
        "features",
        ["tenant_id", "project_id", "state"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_features_project_id"),
        "features",
        ["project_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_features_tenant_id"),
        "features",
        ["tenant_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_features_version_id"),
        "features",
        ["version_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_table(
        "feature_links",
        sa.Column("feature_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.String(length=256), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=256), nullable=True),
        sa.Column("tenant_id", sa.String(length=64), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["omnisense.artifacts.id"],
            name=op.f("fk_feature_links_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["omnisense.features.id"],
            name=op.f("fk_feature_links_feature_id_features"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("feature_id", "artifact_id", name=op.f("pk_feature_links")),
        schema="omnisense",
    )
    op.create_index(
        "ix_feature_links_tenant_artifact_id",
        "feature_links",
        ["tenant_id", "artifact_id"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        "ix_feature_links_tenant_feature_id_method",
        "feature_links",
        ["tenant_id", "feature_id", "method"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_feature_links_method"),
        "feature_links",
        ["method"],
        unique=False,
        schema="omnisense",
    )
    op.create_index(
        op.f("ix_omnisense_feature_links_tenant_id"),
        "feature_links",
        ["tenant_id"],
        unique=False,
        schema="omnisense",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_omnisense_feature_links_tenant_id"), table_name="feature_links", schema="omnisense"
    )
    op.drop_index(
        op.f("ix_omnisense_feature_links_method"), table_name="feature_links", schema="omnisense"
    )
    op.drop_index(
        "ix_feature_links_tenant_feature_id_method", table_name="feature_links", schema="omnisense"
    )
    op.drop_index(
        "ix_feature_links_tenant_artifact_id", table_name="feature_links", schema="omnisense"
    )
    op.drop_table("feature_links", schema="omnisense")
    op.drop_index(
        op.f("ix_omnisense_features_version_id"), table_name="features", schema="omnisense"
    )
    op.drop_index(
        op.f("ix_omnisense_features_tenant_id"), table_name="features", schema="omnisense"
    )
    op.drop_index(
        op.f("ix_omnisense_features_project_id"), table_name="features", schema="omnisense"
    )
    op.drop_index("ix_features_tenant_project_id_state", table_name="features", schema="omnisense")
    op.drop_table("features", schema="omnisense")
    op.drop_index("ix_versions_tenant_project_id_state", table_name="versions", schema="omnisense")
    op.drop_index(
        op.f("ix_omnisense_versions_tenant_id"), table_name="versions", schema="omnisense"
    )
    op.drop_index(
        op.f("ix_omnisense_versions_project_id"), table_name="versions", schema="omnisense"
    )
    op.drop_table("versions", schema="omnisense")
    # ### end Alembic commands ###
